gh issue create --title "Supabase project setup and configuration" --label "high priority" --body ""
gh issue create --title "Database schema (Students, Projects, Skills, Matches) — Supabase" --label "high priority" --body ""
gh issue create --title "Student registration and login — Supabase Auth" --label "high priority" --body ""
gh issue create --title "Teacher/admin login — Supabase Auth" --label "high priority" --body ""
gh issue create --title "Student profile creation (skills, interests, availability)" --label "high priority" --body ""
gh issue create --title "Save profiles to Supabase database" --label "high priority" --body ""
gh issue create --title "Teacher: add project (name, description, required skills, schedule)" --label "high priority" --body ""
gh issue create --title "Teacher: manage/edit projects" --label "high priority" --body ""
gh issue create --title "REST API: POST /student — Node.js/Express" --label "high priority" --body ""
gh issue create --title "REST API: POST /project — Node.js/Express" --label "high priority" --body ""
gh issue create --title "REST API: GET /matches/:studentId — Node.js/Express" --label "high priority" --body ""
gh issue create --title "Match-score algorithm (skills + interests + availability)" --label "high priority" --body ""
gh issue create --title "Generate top 3 match suggestions" --label "high priority" --body ""
gh issue create --title "Deploy — Supabase + Node.js backend, React frontend" --label "high priority" --body ""
gh issue create --title "Edit student profile" --label "medium priority" --body ""
gh issue create --title "Project listing view (visible to students) — React" --label "medium priority" --body ""
gh issue create --title "Sort results by match score" --label "medium priority" --body ""
gh issue create --title "Explainable AI — text explanation for each match" --label "medium priority" --body ""
gh issue create --title "Display match score % and skill overlap (e.g. 3/5)" --label "medium priority" --body ""
gh issue create --title "Form UI for data input — React" --label "medium priority" --body ""
gh issue create --title "Match results list/card view — React" --label "medium priority" --body ""
gh issue create --title "Report (intro, problem, algorithm, implementation, results, discussion)" --label "medium priority" --body ""
gh issue create --title "Bar chart visualization for match results" --label "low priority" --body ""
gh issue create --title "Filters and search" --label "low priority" --body ""
gh issue create --title "Advanced matching algorithms" --label "low priority" --body ""
